### PR TITLE
feat: add `importPath` option to specify import absolute path or relative path

### PR DESCRIPTION
**Pull request by GoodbyeNJN**
### Description

See #492.

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by hannoeru — APPROVED** [review]
LGTM

**Comment by GoodbyeNJN** [comment]
Paths under Windows were not handled correctly, so the test cases were updated to adapt to Windows systems.

**Comment by hannoeru** [comment]
@GoodbyeNJN can u update to latest main branch?

**Comment by GoodbyeNJN** [comment]
Done.

**Review by hannoeru — APPROVED** [review]

**Pull request merged**
