### PR TITLE
feat: generate component name

### LINKED ISSUE #322: KeepAlive component's name which auto generated by route.name
### Description

It was inspired by https://github.com/vuejs/core/issues/4993

### Suggested solution

Use route.name instead of sfc-component's filename as keep-alive component's name

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zhiyuanzmj**
### Description

fixes #322

### Additional context

image

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by hannoeru** [comment]
@zhiyuanzmj  can we have a option to control this?

**Comment by zhiyuanzmj** [comment]
> @zhiyuanzmj can we have a option to control this?

Maybe I should create a new plugin to transform code, for this I need to export `getPageRouteMap` api.

**Comment by zhiyuanzmj** [comment]
> @zhiyuanzmj can we have a option to control this?

How about this pr #331 ?

**Comment by zhiyuanzmj** [comment]
Or what option name should I call it

**Pull request closed without merging**
